### ISSUE TITLE
how to eval on imagenet-v2 as we have 3 different test datasets?

### ISSUE THREAD

**Issue by KosukeTrue** [modestyachts/ImageNetV2#11]
https://paperswithcode.com/sota/image-classification-on-imagenet-v2

as we can see the sota on paperwithcode, but I didn't find which dataset they use. 

[imagenetv2-matched-frequency](https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz)
[imagenetv2-threshold0.7](https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-threshold0.7.tar.gz)
[imagenetv2-topimages](https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-top-images.tar.gz)

**Comment by ludwigschmidt** [comment]
The default one is matched-frequency.
