### ISSUE TITLE
IS AWS needed for evaluation?

### ISSUE THREAD

**Issue by tzzcl** [modestyachts/ImageNetV2#2]
I try to use eval.py to replicate your experiments.

But I get hang on downloading the needed pickle file. 

When I check the boto document, it says that you must provide access key and access token for using boto3.

Is AWS needed or there are some other ways to download the data?

**Comment by ludwigschmidt** [comment]
Currently you need an AWS account for using our metadata classes because they use the boto3 S3 API. Using an AWS account to access our data should not incur any cost however. Hopefully we can also release a version of the code that works without boto3.

**Comment by tzzcl** [comment]
Hi, since we can download files from the website directly. I tried to use wget to replace download_file API in
download_s3_file_with_backoff function, and it works.

Hope it could help improving your code.

**Comment by ludwigschmidt** [comment]
Good to know, thanks!
