### ISSUE TITLE
Make original dataset public

### ISSUE THREAD

**Issue by tissue3** [modestyachts/ImageNetV2#3]
Could you please public the "original" dataset that is not scaled? I need it because flickr seems lost/change some of the images and it's hard to retrieve all non-scaled images now.

**Comment by ludwigschmidt** [comment]
Sorry for the late response. If this is still relevant: are you interested in the images for the candidate pool or one of our three test sets? This summer we decided to take the images for the candidate pool offline because we couldn't guarantee that they don't contain harmful content.
