### ISSUE TITLE
Are the labels the same with ImageNet?

### ISSUE THREAD

**Issue by RogerNi** [modestyachts/ImageNetV2#4]
I tried this dataset on some models trained with ImageNet but got extremely bad accuracy. Later, I find that the class index may not match with ImageNet. Did I do something wrong?

I nearly find the following relationship:
```
Index 0 in V2 ---> 782 screen, CRT screen in original ImageNet
Index 1 in V2 ---> 263 Pembroke, Pembroke Welsh corgi in original ImageNet
```

**Comment by Vaishaal** [comment]
Hello,

Sorry you are having trouble with our dataset! How are you loading the dataset? We 
recently found that the way we distributed the dataset is not consistent with ImageNet Validation. The images in our dataset are organized inside our dataset is (each folder is a class index) :
```
0/ 1/ 2/ ..... 999/
```

The images in val are organized as (each folder is a wordnet id):
```
n01440764/ n01443537/ ...  n15075141/

```
This could cause the class indices to appear different between validation and v2. The class indices are however correct (0/ -> tench, 1/ -> goldfish, etc...).  

Could you try this distribution of our dataset: https://imagenet2datav2.s3-us-west-2.amazonaws.com/imagenet-matched-frequency-format-val.tar.gz. Its organized such that each folder is a wordnet-id, this should make the class indices more consistent.

**Comment by RogerNi** [comment]
Thank you for your reply. I loaded the data manually, not using any tool. I am using this dataset to evaluate the performance of my model. The model follows the ImageNet label mapping: https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a. However, the accuracy is quite low. When looking into the problem, I find that classification is actually done well but only the indices don’t match. So you mean the v2 indices are the same as ImageNet Val? If so, I will go to check whether my model has something wrong. Thank you.

**Comment by Vaishaal** [comment]
Yes our indices should match exactly. If you open the images in folder 0/  you will see they are pictures on tench etc...

Thanks,
Vaishaal Shankar


________________________________

**Comment by RogerNi** [comment]
It turns out that I started the index from 1 but not 0. Thank you for your amazing dataset.

**Comment by tangtaogo** [comment]
> 

The link failed

**Comment by ludwigschmidt** [comment]
Sorry! We're currently in the process of migrating the ImageNetV2 dataset to a new location. Which link are you referring to specifically? Is it https://imagenet2datav2.s3-us-west-2.amazonaws.com/imagenet-matched-frequency-format-val.tar.gz ?
