### ISSUE TITLE
403 Forbidden Error in Download Link

### ISSUE THREAD

**Issue by ddoyoon** [modestyachts/ImageNetV2#5]
Hello! First of all, thank you for sharing your work :) 
I tried downloading the dataset from the link specified in the README (http://imagenetv2public.s3-website-us-west-2.amazonaws.com/) but I'm getting a 403 forbidden error. Would you please look into this?

**Comment by ludwigschmidt** [comment]
Thanks for reaching out! We're currently moving our data off S3 and will update the link shortly. If it would be helpful to have the images as soon as possible, please email Vaishaal and me.

**Comment by ludwigschmidt** [comment]
The links should work again now - please let us know in case you run into any issues.

**Comment by greentec** [comment]
The file name, folder name, etc. are different from the [previous version](https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-topimages.tar.gz). Is there any difference in the data?

**Comment by Vaishaal** [comment]
There is no difference in the data. I made some changes to the names of the folders so they match imagenet wordnet ids as opposed to imagenet class indices.

**Comment by shkarupa-alex** [comment]
Links not working. Again ...

**Comment by Vaishaal** [comment]
Which link specifically?

http://imagenetv2public.s3-website-us-west-2.amazonaws.com works for me.

**Comment by shkarupa-alex** [comment]
This for example https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz

**Comment by Vaishaal** [comment]
Hmm that link works for me and triggers a download.

**Comment by shkarupa-alex** [comment]
Hmmm x2... Now it's working.
But is was unreachable from multiple locations 2 weeks ago
