### ISSUE TITLE
What does it mean, "Ben did none of the work"? 

### ISSUE THREAD

**Issue by mrngbaeb** [modestyachts/ImageNetV2#7]
(stated in the paper) 

Just wondering!

**Comment by ludwigschmidt** [comment]
Sorry for the delay! It means that Ben wasn’t involved in the core experiment. Ben has still been incredibly helpful with encouraging us to pursue this idea, providing resources, and giving feedback at various stages of the project.

**Comment by ShadmanRohan** [comment]
lead author! lol

**Comment by ludwigschmidt** [comment]
The authors are ordered alphabetically :-)

Also this recent publication may be of interest!

https://twitter.com/florian_tramer/status/1642225622368808962

**Comment by AkibSadmanee** [comment]
Noooooo!!! You guys removed Ben!!!
