### ISSUE TITLE
generate_class_info.py uses incorrect constructor for ImageNetData

### ISSUE THREAD

**Issue by mckinziebrandon** [modestyachts/ImageNetV2#9]
Hello, I'm trying to get the mapping from class labels to IDs, and presumably this is done by running `python generate_class_info_file.py` from within the `code` directory (please let me know if this is wrong). 

Upon running this, I hit the following error: 
```
Traceback (most recent call last):
  File "generate_class_info_file.py", line 8, in <module>
    imgnet = imagenet.ImageNetData(load_class_info=False)
TypeError: __init__() got an unexpected keyword argument 'load_class_info'
```
Indeed, imagenet.ImageNetData does not have a kwarg called "load_class_info". Perhaps this code is outdated? 

If there is an easier way for me to simply get the map from label IDs to the original class name strings, please let me know. Thank you!

**Comment by mckinziebrandon** [comment]
I assumed I could also just use the original mapping from [ImageNet2012](https://www.kaggle.com/competitions/imagenet-object-localization-challenge/data?select=LOC_synset_mapping.txt), but wanted to verify / poke around a bit.

**Comment by mckinziebrandon** [comment]
Ah, looks like I can just use [class_info.json](https://github.com/modestyachts/ImageNetV2/blob/master/data/metadata/class_info.json) directly. 

Also, the S3 bucket was hanging for me, FWIW, when I tried just initializing `ImageNetData()` myself in a notebook. My aws/cli credentials should be configured properly.

**Comment by mckinziebrandon** [comment]
Ok, I'm probably doing something dumb here but neither the class_info.json nor the public imagenet label synset mapping seem to correspond to the integer IDs returned when using `datasets.ImageFolder('imagenetv2-top-images-format-val')`. 

Is there another mapping I need to go from the index directory name in your dataset files to the class ID for imagenet? There are 1000 folders here so I (perhaps incorrectly) assumed that directory with name `i` corresponded to imagenet class with label id `i`. 

<img width="809" alt="image" src="https://user-images.githubusercontent.com/11165945/183930163-9a3214f9-956f-4c72-888f-4589451a5605.png">

**Comment by mckinziebrandon** [comment]
Ok, this comment in a previous issue resolved the erroneous mapping issues: https://github.com/modestyachts/ImageNetV2/issues/6#issuecomment-797383723

Anyway, the constructor is still outdated as mentioned in my original post, sorry for going off on an unrelated tangent 🙂

**Comment by Vaishaal** [comment]
Sorry you will need to use the pytorch dataloader here: https://github.com/modestyachts/ImageNetV2_pytorch  to load the dataset.  We don't have compatibility with the ImageFolder dataset currently.
